#!/bin/bash
. /var/openpanel/api/sh/module.sh
. /var/openpanel/modules/Keepalived.module/localfunctions.sh

Module.getconfig() {
    ROUTERID=$(hostname -f)
  cat << _EOF_
  <openpanel.module>
    <dict id="Keepalived" type="class">
      <dict id="keepalived" type="object">
        <enum id="master_slave">master</enum>
        <string id="router_id">${ROUTERID}</string
      </dict>
    </dict>
    <dict id="OpenCORE:Result">
      <integer id="error">0</integer>
      <string id="message">OK</string>
    </dict>
  </openpanel.module>
_EOF_
  exitquiet
}

Module.create() {
    #m_s=$(coreval Keepalived master_slave)

    #[ "${m_s}" = "slave" ] && exiterror "You can not create objects on a slave"

    Module.update

    exitok
}

Module.update() {
    m_s=$(coreval Keepalived master_slave)
    [ "${m_s}" = "slave" ] && exitok

    slave_present=$(coreval Keepalived slave_present)

    GLOBAL_DEFS=$(_create_global)
    VIPCONF=""
    STATICS=""
    VRRPS=""
    :>keepalived.conf

    for uuid in `coreval --loop Keepalived Keepalived:RSPool`; do
        for slbuuid in `coreval --loop Keepalived Keepalived:RSPool ${uuid} Keepalived:SLBMaster`; do
            [ "X${slave_present}" = "X" ] && STATIC=$(_create_vip_static ${uuid} ${slbuuid})
            [ "X${slave_present}" = "X" ] || VRRP=$(_create_vip_vrrp ${uuid} ${slbuuid})
            [ "X${STATIC}" = "X" ]   || STATICS="${STATICS} ${STATIC}"
            [ "X${VRRP}" = "X" ]   || VRRPS="${VRRPS} ${VRRP}"

            VIP=$(_create_vip ${uuid} ${slbuuid})
            VHOST=$(_get_vip_vhost ${uuid} ${slbuuid})
            POOL=$(_create_pool ${uuid} ${VHOST})
            [ "${POOL}" = "nohash" ] && exiterror "Could not create a hash of the URL to check (is the server alive?)"
            VIPCONF="${VIPCONF}\n${VIP}\n${POOL}\n}"
        done
    done

    STATICCONF=$(_create_statics "${STATICS}")
    [ "${STATICCONF}" = "noint" ] && exiterror "Could not determine which interface to use for VIP addresses"

    echo "${GLOBAL_DEFS}" >> keepalived.conf
    [ "X${STATICCONF}" = "X" ] || echo -e "${STATICCONF}" >> keepalived.conf
    echo -e "${VIPCONF}" >> keepalived.conf

    authd installfile keepalived.conf /etc/keepalived/
    authd reloadservice keepalived
    exitok
}

Module.delete() {
    Module.update
    exitok
}

Keepalived:Slave.listobjects() {
    USERID=$(id -u openpanel-ha 2> /dev/null)
    [ "X${USERID}" = "X" ] && authd runscript keepalived-create-slave-user

    if [ ! -f /etc/openpanel/ha/id_rsa ]; then
        rm -f id_rsa id_rsa.pub 
        ssh-keygen -f ./id_rsa -t rsa -q -N ""
        authd makedir /etc/openpanel/ha
        authd installfile id_rsa /etc/openpanel/ha
        authd installfile id_rsa.pub /etc/openpanel/ha
    fi

    slave_prio=$(cat /etc/openpanel/ha/prio)
    slave_master_ip=$(cat /etc/openpanel/ha/master)
    slave_key=$(cat /etc/openpanel/ha/id_rsa.pub)
    
    cat << _EOF_
<?xml version="1.0" encoding="UTF-8"?>
<dict>
  <dict id="objects">
    <dict id="Keepalived:Slave" type="class">
      <dict id="kslave" type="object">
        <string id="slave_prio">${slave_prio}</string>
        <string id="slave_master_ip">${slave_master_ip}</string>
        <textarea id="slave_key">${slave_key}</textarea>
	<string id="class">Keepalived:Slave</string>
      </dict>
    </dict>
  </dict>
  <dict id="OpenCORE:Result">
    <integer id="error">0</integer>
    <string id="message">OK</string>
  </dict>
</dict>
_EOF_

    exitok
}

Keepalived:Slave.update() {
    slave_prio=$(coreval Keepalived:Slave slave_prio)
    slave_master_ip=$(coreval Keepalived:Slave slave_master_ip)
    slave_key=$(coreval Keepalived:Slave slave_key)

    echo ${slave_prio} > prio
    echo slave_master_ip > slave_master_ip

    authd installfile prio /etc/openpanel/ha
    authd installfile slave_master_ip /etc/openpanel/ha
}

implement Keepalived.module
