#!/usr/bin/env python

"""This script creates a Ubuntu/Debian startupscript for NAT on the VRRP-NAT-gw"""

from ipaddr import IPNetwork, IPAddress
import sys
import subprocess

gw=""

if (len(sys.argv) == 4):
    if ( sys.argv[1] != None):
        gw = sys.argv[1]
    if ( sys.argv[2] != None):
        ext_iface = sys.argv[2]
    if ( sys.argv[3] != None):
        int_iface = sys.argv[3]
else:
    sys.exit(1)

ipaddr = IPNetwork(gw+"/24")

conffile="/etc/openpanel/ha/nat-gw"
fileexisted = "false"

if os.path.exists(conffile):
    fileexisted = "true"

f = open(conffile, 'w')
f.write("SNET=\"%s/%s\"\n" % ( str(ipaddr.network), str(ipaddr.prefixlen) ))
f.write("E_IFACE=\"%s\"\n" % ( str(ext_iface) ))
f.write("I_IFACE=\"%s\"\n" % ( str(int_iface) ))
f.close();

if fileexisted != "true":
    subprocess.call(["/usr/sbin/update-rc.d", "keepalived-nat-gw", "defaults"])
    subprocess.call(["/etc/init.d/keepalived-nat-gw", "start"])
else:
    subprocess.call(["/etc/init.d/keepalived-nat-gw", "start"])

